# EV Vehicle Distribution Visualization

In [1]:
import pandas as pd

df_LAD_to_ITL = pd.read_csv('./LAD_to_ITL(2021).csv')
df_LAD_to_ITL

,LAD21CD,LAD21NM,LAU121CD,LAU121NM,ITL321CD,ITL321NM,ITL221CD,ITL221NM,ITL121CD,ITL121NM,ObjectId
0,E06000001,Hartlepool,E06000001,Hartlepool,TLC11,Hartlepool and Stockton-on-Tees,TLC1,Tees Valley and Durham,TLC,North East (England),1
1,E06000004,Stockton-on-Tees,E06000004,Stockton-on-Tees,TLC11,Hartlepool and Stockton-on-Tees,TLC1,Tees Valley and Durham,TLC,North East (England),2
2,E06000002,Middlesbrough,E06000002,Middlesbrough,TLC12,South Teesside,TLC1,Tees Valley and Durham,TLC,North East (England),3
3,E06000003,Redcar and Cleveland,E06000003,Redcar and Cleveland,TLC12,South Teesside,TLC1,Tees Valley and Durham,TLC,North East (England),4
4,E06000005,Darlington,E06000005,Darlington,TLC13,Darlington,TLC1,Tees Valley and Durham,TLC,North East (England),5
...,...,...,...,...,...,...,...,...,...,...,...
383,E07000106,Canterbury,E07000106,Canterbury,TLJ44,East Kent,TLJ4,Kent,TLJ,South East (England),384
384,E07000108,Dover,E07000108,Dover,TLJ44,East Kent,TLJ4,Kent,TLJ,South East (England),385
385,E07000112,Folkestone and Hythe,E07000112,Folkestone and Hythe,TLJ44,East Kent,TLJ4,Kent,TLJ,South East (England),386
386,E07000114,Thanet,E07000114,Thanet,TLJ44,East Kent,TLJ4,Kent,TLJ,South East (England),387
387,E07000105,Ashford,E07000105,Ashford,TLJ45,Mid Kent,TLJ4,Kent,TLJ,South East (England),388

In [2]:
df_LAD_to_ITL['NUTS_ID'] = df_LAD_to_ITL['ITL321CD'].astype(str).str.replace('^TL', 'UK', regex=True)
df_LAD_to_ITL.rename(columns={'LAD21CD': 'ONScode'}, inplace=True)
df_LAD_to_ITL

,ONScode,LAD21NM,LAU121CD,LAU121NM,ITL321CD,ITL321NM,ITL221CD,ITL221NM,ITL121CD,ITL121NM,ObjectId,NUTS_ID
0,E06000001,Hartlepool,E06000001,Hartlepool,TLC11,Hartlepool and Stockton-on-Tees,TLC1,Tees Valley and Durham,TLC,North East (England),1,UKC11
1,E06000004,Stockton-on-Tees,E06000004,Stockton-on-Tees,TLC11,Hartlepool and Stockton-on-Tees,TLC1,Tees Valley and Durham,TLC,North East (England),2,UKC11
2,E06000002,Middlesbrough,E06000002,Middlesbrough,TLC12,South Teesside,TLC1,Tees Valley and Durham,TLC,North East (England),3,UKC12
3,E06000003,Redcar and Cleveland,E06000003,Redcar and Cleveland,TLC12,South Teesside,TLC1,Tees Valley and Durham,TLC,North East (England),4,UKC12
4,E06000005,Darlington,E06000005,Darlington,TLC13,Darlington,TLC1,Tees Valley and Durham,TLC,North East (England),5,UKC13
...,...,...,...,...,...,...,...,...,...,...,...,...
383,E07000106,Canterbury,E07000106,Canterbury,TLJ44,East Kent,TLJ4,Kent,TLJ,South East (England),384,UKJ44
384,E07000108,Dover,E07000108,Dover,TLJ44,East Kent,TLJ4,Kent,TLJ,South East (England),385,UKJ44
385,E07000112,Folkestone and Hythe,E07000112,Folkestone and Hythe,TLJ44,East Kent,TLJ4,Kent,TLJ,South East (England),386,UKJ44
386,E07000114,Thanet,E07000114,Thanet,TLJ44,East Kent,TLJ4,Kent,TLJ,South East (England),387,UKJ44
387,E07000105,Ashford,E07000105,Ashford,TLJ45,Mid Kent,TLJ4,Kent,TLJ,South East (England),388,UKJ45

In [5]:
ONS_NUTS3_mapping = dict(zip(df_LAD_to_ITL['ONScode'], df_LAD_to_ITL['NUTS_ID']))

Car = pd.read_csv('./LicensedPlugInVehiclesCarsVEH0142_UK_DfT_Poly_2023_7344901567442451546.csv')
HGV = pd.read_csv('./LicensedPlugInVehiclesHGVVEH0142_UK_DfT_Poly_2023_-4512007299528620992.csv')
LGV = pd.read_csv('./LicensedPlugInVehiclesLGVVEH0142_UK_DfT_Poly_2023_2502161826204229057.csv')
Buscoach = pd.read_csv('./LicensedPlugInVehiclesBusCoachVEH0142_UK_DfT_Poly_2023_4835146115508310650.csv')

Car['NUTS_ID'] = Car['ONScode'].map(ONS_NUTS3_mapping)
HGV['NUTS_ID'] = HGV['ONScode'].map(ONS_NUTS3_mapping)
LGV['NUTS_ID'] = LGV['ONScode'].map(ONS_NUTS3_mapping)
Buscoach['NUTS_ID'] = Buscoach['ONScode'].map(ONS_NUTS3_mapping)

Car

,FID,ONScode,ONSname,Region,BodyType,Battery electric (Company),Battery electric (Private),Battery electric (Total),Plug-in hybrid electric (diesel) (Company),Plug-in hybrid electric (diesel) (Private),...,Plug-in hybrid electric (petrol) (Total),Range extended electric (Company),Range extended electric (Private),Range extended electric (Total),Total (Company),Total (Private),Total (Total),Shape__Area,Shape__Length,NUTS_ID
0,1,E06000001,Hartlepool,North East,Cars,139,280,419,1,1,...,217,0,4,4,176,466,642,9.371703e+07,70995.173776,UKC11
1,2,E06000002,Middlesbrough,North East,Cars,186,301,487,1,4,...,257,2,3,5,252,502,754,5.388156e+07,44479.646370,UKC12
2,3,E06000003,Redcar and Cleveland,North East,Cars,178,410,588,2,4,...,262,0,9,9,214,651,865,2.450695e+08,96703.510654,UKC12
3,4,E06000004,Stockton-on-Tees,North East,Cars,409,893,1302,6,13,...,658,1,9,10,596,1393,1989,2.049329e+08,123404.959102,UKC11
4,5,E06000005,Darlington,North East,Cars,311,480,791,0,4,...,428,0,8,8,458,773,1231,1.974778e+08,107202.299425,UKC13
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,W06000020,Torfaen,Wales,Cars,188,348,536,1,3,...,185,0,14,14,225,514,739,1.262399e+08,82540.039297,UKL16
370,371,W06000021,Monmouthshire,Wales,Cars,179,758,937,0,11,...,493,2,19,21,240,1222,1462,8.503277e+08,224909.141030,UKL21
371,372,W06000022,Newport,Wales,Cars,330,717,1047,1,5,...,471,1,18,19,434,1109,1543,1.904311e+08,153213.179656,UKL21
372,373,W06000023,Powys,Wales,Cars,205,632,837,1,4,...,502,1,30,31,313,1062,1375,5.195311e+09,610076.853820,UKL24
373,374,W06000024,Merthyr Tydfil,Wales,Cars,92,123,215,0,1,...,108,0,0,0,119,205,324,1.119570e+08,66689.081059,UKL15